# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    rate_limiter:
        notifications_user:
            policy: 'fixed_window'
            limit: '%env(int:NOTIFICATIONS_LIMIT_PER_HOUR)%'
            interval: '60 minutes'

    messenger:
        transports:
            async:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    delay: 60000
                    multiplier: 2
                    max_delay: 600000
        routing:
            'App\NotificationPublisher\Application\Message\SendNotificationMessage': async

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
